import { boolean, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { BuildSpec } from "@zhanlu/build-portal-contracts";

export const phaseEnum = pgEnum("build_phase", ["preview_queued", "previewing", "awaiting_confirmation", "queued", "source_sync_preview", "source_sync", "preflight", "release_prepare", "dispatching", "running", "succeeded", "failed", "cancelled", "needs_attention"]);

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), username: text("username").notNull(), passwordHash: text("password_hash").notNull(), disabled: boolean("disabled").default(false).notNull(), ...timestamps }, (table) => [uniqueIndex("users_username_uq").on(table.username)]);
export const sessions = pgTable("sessions", { id: text("id").primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), csrfHash: text("csrf_hash").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("sessions_expires_idx").on(table.expiresAt)]);
export const loginAttempts = pgTable("login_attempts", { id: uuid("id").defaultRandom().primaryKey(), username: text("username").notNull(), ipHash: text("ip_hash").notNull(), succeeded: boolean("succeeded").notNull(), attemptedAt: timestamp("attempted_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("login_attempts_window_idx").on(table.username, table.ipHash, table.attemptedAt)]);

export const builds = pgTable("builds", { id: uuid("id").defaultRandom().primaryKey(), requestId: uuid("request_id").defaultRandom().notNull(), spec: jsonb("spec").$type<BuildSpec>().notNull(), resolved: jsonb("resolved").$type<Record<string, unknown>>(), confirmationHash: text("confirmation_hash"), phase: phaseEnum("phase").default("preview_queued").notNull(), phaseReason: text("phase_reason"), requestedBy: uuid("requested_by").references(() => users.id), confirmedAt: timestamp("confirmed_at", { withTimezone: true }), leaseOwner: text("lease_owner"), leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }), releaseUrl: text("release_url"), cancelRequestedAt: timestamp("cancel_requested_at", { withTimezone: true }), ...timestamps }, (table) => [uniqueIndex("builds_request_id_uq").on(table.requestId), index("builds_claim_idx").on(table.phase, table.leaseExpiresAt)]);
export const buildRuns = pgTable("build_runs", { id: uuid("id").defaultRandom().primaryKey(), buildId: uuid("build_id").references(() => builds.id, { onDelete: "cascade" }).notNull(), platform: text("platform").notNull(), workflow: text("workflow").notNull(), runId: text("run_id"), runUrl: text("run_url"), status: text("status").default("pending").notNull(), conclusion: text("conclusion"), failedJobs: jsonb("failed_jobs").$type<string[]>().default([]).notNull(), dispatchAttempts: integer("dispatch_attempts").default(0).notNull(), ...timestamps }, (table) => [uniqueIndex("build_runs_platform_uq").on(table.buildId, table.platform)]);
export const buildEvents = pgTable("build_events", { id: uuid("id").defaultRandom().primaryKey(), buildId: uuid("build_id").references(() => builds.id, { onDelete: "cascade" }).notNull(), sequence: integer("sequence").notNull(), level: text("level").default("info").notNull(), event: text("event").notNull(), data: jsonb("data").$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("build_events_sequence_uq").on(table.buildId, table.sequence)]);

export const schedules = pgTable("schedules", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), cron: text("cron").notNull(), timezone: text("timezone").default("Asia/Tokyo").notNull(), enabled: boolean("enabled").default(true).notNull(), spec: jsonb("spec").$type<BuildSpec>().notNull(), revision: integer("revision").default(1).notNull(), createdBy: uuid("created_by").references(() => users.id), ...timestamps });
export const scheduleRevisions = pgTable("schedule_revisions", { scheduleId: uuid("schedule_id").references(() => schedules.id, { onDelete: "cascade" }).notNull(), revision: integer("revision").notNull(), snapshot: jsonb("snapshot").$type<Record<string, unknown>>().notNull(), createdBy: uuid("created_by").references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [primaryKey({ columns: [table.scheduleId, table.revision] })]);
export const scheduleOccurrences = pgTable("schedule_occurrences", { id: uuid("id").defaultRandom().primaryKey(), scheduleId: uuid("schedule_id").references(() => schedules.id, { onDelete: "cascade" }).notNull(), scheduledFor: timestamp("scheduled_for", { withTimezone: true }).notNull(), buildId: uuid("build_id").references(() => builds.id), status: text("status").default("created").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("schedule_occurrences_uq").on(table.scheduleId, table.scheduledFor)]);
export const refSnapshots = pgTable("ref_snapshots", { id: uuid("id").defaultRandom().primaryKey(), repository: text("repository").notNull(), provider: text("provider").notNull(), ref: text("ref").notNull(), sha: text("sha").notNull(), syncStatus: text("sync_status").notNull(), capturedAt: timestamp("captured_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("ref_snapshots_latest_idx").on(table.repository, table.provider, table.capturedAt)]);
export const workers = pgTable("workers", { id: text("id").primaryKey(), version: text("version").notNull(), currentBuildId: uuid("current_build_id").references(() => builds.id), heartbeatAt: timestamp("heartbeat_at", { withTimezone: true }).defaultNow().notNull(), startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull() });
export const auditEvents = pgTable("audit_events", { id: uuid("id").defaultRandom().primaryKey(), actorId: uuid("actor_id").references(() => users.id), action: text("action").notNull(), targetType: text("target_type").notNull(), targetId: text("target_id"), ipHash: text("ip_hash"), data: jsonb("data").$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("audit_events_created_idx").on(table.createdAt)]);
