apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zhanlu-build
resources:
  - namespace.yaml
  - applications.yaml
  - backup.yaml
  - network-policy.yaml
configMapGenerator:
  - name: build-portal-caddy
    files: [Caddyfile=Caddyfile]
generatorOptions:
  disableNameSuffixHash: true
