import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { authenticate, audit, AuthError, ipHash, login, logout, rotateCsrf, SESSION_COOKIE, sessionCookie, verifyCsrf, verifyOrigin } from "@zhanlu/build-portal-auth";
import { buildSpecSchema, confirmationHash, resolveReleaseVersion, scheduleInputSchema } from "@zhanlu/build-portal-contracts";
import { getPool } from "@zhanlu/build-portal-db";
import { CronExpressionParser } from "cron-parser";

export const runtime = "nodejs";
const json = (value: unknown, status = 200) => NextResponse.json(value, { status, headers: { "cache-control": "no-store" } });
const clientIp = (request: NextRequest) => request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? "unknown";
const buildRefRepositories = ["zhanlu-code", "zhanlu-core", "zhanlu-vs"] as const;
const nextRunAt = (cron: string, timezone: string): string | null => {
  try { return CronExpressionParser.parse(cron, { currentDate: new Date(), tz: timezone }).next().toDate().toISOString(); } catch { return null; }
};

async function body(request: NextRequest): Promise<unknown> { try { return await request.json(); } catch { throw new HttpError("invalid JSON body", 400); } }
function buildId(path: string[], suffix?: string): string | null { return path[0] === "builds" && path[1] && (!suffix || path[2] === suffix) ? path[1] : null; }
function scheduleId(path: string[], suffix?: string): string | null { return path[0] === "schedules" && path[1] && (!suffix || path[2] === suffix) ? path[1] : null; }

async function handler(request: NextRequest, context: { params: Promise<{ path: string[] }> }) {
  const { path } = await context.params; const route = path.join("/"); const method = request.method;
  if (route === "health/live") return json({ status: "ok" });
  if (route === "health/ready") { try { await getPool().query("SELECT 1"); return json({ status: "ready" }); } catch { return json({ status: "not_ready" }, 503); } }
  if (route === "auth/login" && method === "POST") { if (!verifyOrigin(request.headers.get("origin"))) throw new HttpError("invalid origin", 403); const value = await body(request) as Record<string, unknown>; const result = await login(String(value.username ?? ""), String(value.password ?? ""), clientIp(request)); const response = json({ user: result.user, csrfToken: result.csrfToken }); response.headers.set("set-cookie", sessionCookie(result.sessionId)); return response; }

  const session = await authenticate(request.cookies.get(SESSION_COOKIE)?.value);
  if (!session) throw new HttpError("authentication required", 401);
  if (route === "metrics" && method === "GET") { const counts = await getPool().query("SELECT phase, count(*)::int AS count FROM builds GROUP BY phase"); return new NextResponse(counts.rows.map((row) => `zhanlu_builds{phase=\"${row.phase}\"} ${row.count}`).join("\n") + "\n", { headers: { "content-type": "text/plain; version=0.0.4", "cache-control": "no-store" } }); }
  if (route === "auth/me" && method === "GET") return json({ user: { id: session.userId, username: session.username }, csrfToken: await rotateCsrf(session) });
  if (method !== "GET") { if (!verifyOrigin(request.headers.get("origin")) || !verifyCsrf(session, request.headers.get("x-csrf-token") ?? undefined)) throw new HttpError("CSRF validation failed", 403); }
  if (route === "auth/logout" && method === "POST") { await logout(session.sessionId); const response = json({ ok: true }); response.headers.set("set-cookie", sessionCookie("", true)); return response; }

  if (route === "refs" && method === "GET") { const result = await getPool().query("SELECT DISTINCT ON(repository,provider,ref) repository,provider,ref,sha,sync_status,captured_at FROM ref_snapshots WHERE repository = ANY($1::text[]) ORDER BY repository,provider,ref,captured_at DESC", [buildRefRepositories]); return json({ refs: result.rows }); }
  if (route === "refs/refresh" && method === "POST") { await audit(session.userId, "refs.refresh.requested", "refs", null, ipHash(clientIp(request))); return json({ accepted: true }, 202); }
  if (route === "build-previews" && method === "POST") {
    const spec = buildSpecSchema.parse(await body(request)); if(spec.triggerOnly)throw new HttpError("triggerOnly is reserved for failed/cancelled platform retry",400);const requestId = randomUUID(); const resolvedVersion = resolveReleaseVersion(spec); const snapshot = await getPool().query("SELECT DISTINCT ON(repository,provider,ref) repository,provider,ref,sha,sync_status,captured_at FROM ref_snapshots WHERE repository = ANY($1::text[]) ORDER BY repository,provider,ref,captured_at DESC", [buildRefRepositories]);
    const resolved = { ...resolvedVersion, refs: { sourceBranch: spec.sourceBranch, zhanluCoreRef: spec.zhanluCoreRef, zhanluVsRef: spec.zhanluVsRef }, deliveryProfile: spec.deliveryProfile, platforms: spec.platform === "all" ? ["macos","linux","windows"] : [spec.platform], syncScope: [spec.sourceBranch,spec.zhanluCoreRef,spec.zhanluVsRef].some((ref) => ref !== "develop") ? "all-refs" : "default-branches", githubVisibility: spec.publish ? "published" : "draft", syncGitLab: spec.kind === "formal" && spec.syncGitLab, refSnapshot: snapshot.rows };
    const hash = confirmationHash({ spec, resolved }, process.env.CONFIRMATION_SECRET ?? ""); if (!process.env.CONFIRMATION_SECRET) throw new Error("CONFIRMATION_SECRET is required");
    const inserted = await getPool().query("INSERT INTO builds(request_id,spec,resolved,confirmation_hash,phase,requested_by) VALUES($1,$2::jsonb,$3::jsonb,$4,'awaiting_confirmation',$5) RETURNING *", [requestId, JSON.stringify(spec), JSON.stringify(resolved), hash, session.userId]);
    await audit(session.userId, "build.preview", "build", inserted.rows[0].id, ipHash(clientIp(request)), { requestId }); return json({ build: inserted.rows[0] }, 201);
  }
  if (route === "builds" && method === "GET") { const result = await getPool().query("SELECT b.id,b.request_id,b.spec,b.resolved,b.confirmation_hash,b.phase,b.phase_reason,b.release_url,b.created_at,b.updated_at,u.username AS requested_by_username FROM builds b LEFT JOIN users u ON u.id=b.requested_by ORDER BY b.created_at DESC LIMIT 100"); return json({ builds: result.rows }); }
  const id = buildId(path);
  if (id && path.length === 2 && method === "GET") { const build = await getPool().query("SELECT b.*,u.username AS requested_by_username FROM builds b LEFT JOIN users u ON u.id=b.requested_by WHERE b.id=$1", [id]); if (!build.rows[0]) throw new HttpError("build not found", 404); const [runs, events] = await Promise.all([getPool().query("SELECT * FROM build_runs WHERE build_id=$1 ORDER BY platform", [id]), getPool().query("SELECT * FROM build_events WHERE build_id=$1 ORDER BY sequence", [id])]); return json({ build: build.rows[0], runs: runs.rows, events: events.rows }); }
  const confirmId = buildId(path, "confirm");
  if (confirmId && method === "POST") { const value = await body(request) as Record<string, unknown>; const build = await getPool().query("SELECT * FROM builds WHERE id=$1 FOR UPDATE", [confirmId]); const row = build.rows[0]; if (!row) throw new HttpError("build not found", 404); if (row.phase !== "awaiting_confirmation") throw new HttpError("build is not awaiting confirmation", 409); if (value.confirmationHash !== row.confirmation_hash) throw new HttpError("preview changed or confirmation hash is invalid", 409); if (row.spec.publish && value.phrase !== `FORMAL ${row.resolved.releaseVersion}`) throw new HttpError("formal publish confirmation phrase does not match", 409); await getPool().query("UPDATE builds SET phase='queued',confirmed_at=now(),updated_at=now() WHERE id=$1", [confirmId]); await audit(session.userId, row.spec.publish ? "build.formal_publish_confirm" : "build.confirm", "build", confirmId, ipHash(clientIp(request))); return json({ phase: "queued" }); }
  const cancelId = buildId(path, "cancel");
  if (cancelId && method === "POST") { await getPool().query("UPDATE builds SET cancel_requested_at=now(),phase=CASE WHEN phase IN ('preview_queued','previewing','awaiting_confirmation','queued') THEN 'cancelled' ELSE phase END,updated_at=now() WHERE id=$1", [cancelId]); await audit(session.userId, "build.cancel", "build", cancelId, ipHash(clientIp(request))); return json({ accepted: true }); }
  const retryId = buildId(path, "retry");
  if (retryId && method === "POST") { const value = await body(request) as Record<string, unknown>; const platforms = Array.isArray(value.platforms) ? value.platforms : []; const changed = await getPool().query("UPDATE build_runs SET status='pending',conclusion=NULL,failed_jobs='[]',run_id=NULL,run_url=NULL,updated_at=now() WHERE build_id=$1 AND platform=ANY($2::text[]) AND conclusion IN ('failure','cancelled') RETURNING platform", [retryId, platforms]); if (!changed.rowCount) throw new HttpError("no failed or cancelled platform selected", 409); await getPool().query("UPDATE builds SET phase='queued',phase_reason='retry',updated_at=now() WHERE id=$1", [retryId]); await audit(session.userId, "build.retry", "build", retryId, ipHash(clientIp(request)), { platforms }); return json({ platforms: changed.rows.map((row) => row.platform) }); }

  if (route === "schedules" && method === "GET") { const result = await getPool().query("SELECT * FROM schedules WHERE archived_at IS NULL ORDER BY created_at DESC"); return json({ schedules: result.rows.map((row) => ({ ...row, next_run_at: row.enabled ? nextRunAt(row.cron, row.timezone) : null })) }); }
  if (route === "schedules" && method === "POST") { const value = scheduleInputSchema.parse(await body(request)); const inserted = await getPool().query("INSERT INTO schedules(name,cron,timezone,enabled,spec,created_by) VALUES($1,$2,$3,$4,$5::jsonb,$6) RETURNING *", [value.name,value.cron,value.timezone,value.enabled,JSON.stringify(value.spec),session.userId]); await getPool().query("INSERT INTO schedule_revisions(schedule_id,revision,snapshot,created_by) VALUES($1,1,$2::jsonb,$3)", [inserted.rows[0].id,JSON.stringify(value),session.userId]); await audit(session.userId,"schedule.create","schedule",inserted.rows[0].id,ipHash(clientIp(request))); return json({ schedule: inserted.rows[0] },201); }
  const sid = scheduleId(path);
  if (sid && path.length === 2 && method === "PATCH") { const value = scheduleInputSchema.partial().parse(await body(request)); const current = await getPool().query("SELECT * FROM schedules WHERE id=$1 AND archived_at IS NULL",[sid]); if (!current.rows[0]) throw new HttpError("schedule not found",404); const merged = scheduleInputSchema.parse({ ...current.rows[0], ...value }); const updated = await getPool().query("UPDATE schedules SET name=$2,cron=$3,timezone=$4,enabled=$5,spec=$6::jsonb,revision=revision+1,updated_at=now() WHERE id=$1 AND archived_at IS NULL RETURNING *",[sid,merged.name,merged.cron,merged.timezone,merged.enabled,JSON.stringify(merged.spec)]); await getPool().query("INSERT INTO schedule_revisions(schedule_id,revision,snapshot,created_by) VALUES($1,$2,$3::jsonb,$4)",[sid,updated.rows[0].revision,JSON.stringify(merged),session.userId]); await audit(session.userId,"schedule.update","schedule",sid,ipHash(clientIp(request)),{revision:updated.rows[0].revision}); return json({ schedule: updated.rows[0] }); }
  if (sid && path.length === 2 && method === "DELETE") { const archived = await getPool().query("UPDATE schedules SET archived_at=now(),enabled=false,updated_at=now() WHERE id=$1 AND archived_at IS NULL RETURNING id",[sid]); if (!archived.rows[0]) throw new HttpError("schedule not found",404); await audit(session.userId,"schedule.archive","schedule",sid,ipHash(clientIp(request))); return json({ ok:true, archived:true }); }
  const runNowId = scheduleId(path,"run-now");
  if (runNowId && method === "POST") { const current = await getPool().query("SELECT spec FROM schedules WHERE id=$1 AND archived_at IS NULL",[runNowId]); if (!current.rows[0]) throw new HttpError("schedule not found",404); const parsed = buildSpecSchema.parse(current.rows[0].spec); const resolvedVersion = resolveReleaseVersion(parsed); const spec = parsed.timePatch ? parsed : { ...parsed, timePatch: resolvedVersion.timePatch }; const resolved = { ...resolveReleaseVersion(spec), platforms: spec.platform === "all" ? ["macos", "linux", "windows"] : [spec.platform] }; const build = await getPool().query("INSERT INTO builds(spec,resolved,phase,requested_by,confirmed_at) VALUES($1::jsonb,$2::jsonb,'queued',$3,now()) RETURNING id",[JSON.stringify(spec),JSON.stringify(resolved),session.userId]); await audit(session.userId,"schedule.run_now","schedule",runNowId,ipHash(clientIp(request)),{buildId:build.rows[0].id}); return json({ buildId:build.rows[0].id },202); }
  throw new HttpError("route not found", 404);
}

class HttpError extends Error { constructor(message: string, readonly status: number) { super(message); } }
async function dispatch(request: NextRequest, context: { params: Promise<{ path: string[] }> }) { try { return await handler(request, context); } catch (error) { if (error instanceof HttpError || error instanceof AuthError) return json({ error: error.message }, error.status); if (error && typeof error === "object" && "issues" in error) return json({ error: "validation failed", issues: (error as {issues: unknown}).issues },400); console.error("request failed", error instanceof Error ? error.message : "unknown"); return json({ error: "internal error" },500); } }
export const GET=dispatch; export const POST=dispatch; export const PATCH=dispatch; export const DELETE=dispatch;
