CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE build_phase AS ENUM ('preview_queued','previewing','awaiting_confirmation','queued','source_sync_preview','source_sync','preflight','release_prepare','dispatching','running','succeeded','failed','cancelled','needs_attention'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username text NOT NULL UNIQUE, password_hash text NOT NULL, disabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (id text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, csrf_hash text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS login_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username text NOT NULL, ip_hash text NOT NULL, succeeded boolean NOT NULL, attempted_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS login_attempts_window_idx ON login_attempts(username, ip_hash, attempted_at);

CREATE TABLE IF NOT EXISTS builds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE, spec jsonb NOT NULL, resolved jsonb, confirmation_hash text, phase build_phase NOT NULL DEFAULT 'preview_queued', phase_reason text, requested_by uuid REFERENCES users(id), confirmed_at timestamptz, lease_owner text, lease_expires_at timestamptz, release_url text, cancel_requested_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS builds_claim_idx ON builds(phase, lease_expires_at);
CREATE TABLE IF NOT EXISTS build_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), build_id uuid NOT NULL REFERENCES builds(id) ON DELETE CASCADE, platform text NOT NULL, workflow text NOT NULL, run_id text, run_url text, status text NOT NULL DEFAULT 'pending', conclusion text, failed_jobs jsonb NOT NULL DEFAULT '[]', dispatch_attempts integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(build_id, platform));
CREATE TABLE IF NOT EXISTS build_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), build_id uuid NOT NULL REFERENCES builds(id) ON DELETE CASCADE, sequence integer NOT NULL, level text NOT NULL DEFAULT 'info', event text NOT NULL, data jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(build_id, sequence));

CREATE TABLE IF NOT EXISTS schedules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, cron text NOT NULL, timezone text NOT NULL DEFAULT 'Asia/Tokyo', enabled boolean NOT NULL DEFAULT true, spec jsonb NOT NULL, revision integer NOT NULL DEFAULT 1, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS schedule_revisions (schedule_id uuid NOT NULL REFERENCES schedules(id) ON DELETE CASCADE, revision integer NOT NULL, snapshot jsonb NOT NULL, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(schedule_id, revision));
CREATE TABLE IF NOT EXISTS schedule_occurrences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schedule_id uuid NOT NULL REFERENCES schedules(id) ON DELETE CASCADE, scheduled_for timestamptz NOT NULL, build_id uuid REFERENCES builds(id), status text NOT NULL DEFAULT 'created', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(schedule_id, scheduled_for));
CREATE TABLE IF NOT EXISTS ref_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), repository text NOT NULL, provider text NOT NULL, ref text NOT NULL, sha text NOT NULL, sync_status text NOT NULL, captured_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ref_snapshots_latest_idx ON ref_snapshots(repository, provider, captured_at DESC);
CREATE TABLE IF NOT EXISTS workers (id text PRIMARY KEY, version text NOT NULL, current_build_id uuid REFERENCES builds(id), heartbeat_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES users(id), action text NOT NULL, target_type text NOT NULL, target_id text, ip_hash text, data jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_events_created_idx ON audit_events(created_at DESC);
