"use client";
import { useEffect, useState } from "react";

type Build = { id: string; spec: { version: string; platform: string; kind: string; publish?: boolean }; resolved?: { releaseVersion?: string }; confirmation_hash?: string; phase: string; created_at: string; release_url?: string };
export default function Home() {
  const [csrf, setCsrf] = useState(""); const [builds, setBuilds] = useState<Build[]>([]); const [refs,setRefs]=useState<string[]>([]);const [message, setMessage] = useState("");
  const refresh = () => fetch("/api/builds").then((r) => r.ok ? r.json() : Promise.reject()).then((v) => setBuilds(v.builds)).catch(() => undefined);
  useEffect(() => { fetch("/api/auth/me").then((r)=>r.ok?r.json():Promise.reject()).then((value)=>{setCsrf(value.csrfToken);void fetch("/api/refs").then((r)=>r.json()).then((data)=>setRefs([...new Set<string>(data.refs.map((item:{ref:string})=>item.ref))]));return refresh();}).catch(()=>undefined); }, []);
  async function login(form: FormData) { const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json", origin: location.origin }, body: JSON.stringify(Object.fromEntries(form)) }); const value = await response.json(); if (!response.ok) return setMessage(value.error); setCsrf(value.csrfToken); setMessage("登录成功"); void refresh(); }
  async function preview(form: FormData) { const raw = Object.fromEntries(form); const spec = { ...raw, bundleCodexRuntime: raw.bundleCodexRuntime === "on", triggerOnly: false, syncGitLab: raw.kind === "formal" && raw.syncGitLab === "on", publish: raw.publish === "on" }; const response = await fetch("/api/build-previews", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrf, origin: location.origin }, body: JSON.stringify(spec) }); const value = await response.json(); setMessage(response.ok ? `预览已创建：${value.build.resolved.releaseVersion}` : value.error); void refresh(); }
  async function action(build: Build, operation: "confirm"|"cancel"|"retry") { const payload: Record<string,unknown>={}; if(operation==="confirm"){payload.confirmationHash=build.confirmation_hash;if(build.spec.publish)payload.phrase=prompt(`输入 FORMAL ${build.resolved?.releaseVersion}`)??"";}if(operation==="retry")payload.platforms=build.spec.platform==="all"?["macos","linux","windows"]:[build.spec.platform];const response=await fetch(`/api/builds/${build.id}/${operation}`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf,origin:location.origin},body:JSON.stringify(payload)});const value=await response.json();setMessage(response.ok?`${operation} 已接受`:value.error);void refresh();}
  return <div className="grid"><section className="panel"><h1>创建 Stable 构建</h1><p className="muted">预览不会写远端；确认后 Worker 才会同步并触发工作流。</p><form action={preview}><datalist id="refs">{refs.map((ref)=><option key={ref} value={ref}/>)}</datalist><div className="fields"><label>类型<select name="kind"><option value="development">Development</option><option value="formal">Formal</option></select></label><label>版本<input name="version" required placeholder="1.4.1" /></label><label>平台<select name="platform"><option value="all">全部</option><option value="linux">Linux</option><option value="macos">macOS</option><option value="windows">Windows</option></select></label><label>输出<select name="outputMode"><option value="workflow-artifact">Workflow artifact</option><option value="release">Draft release</option></select></label><label>源码分支<input name="sourceBranch" list="refs" defaultValue="develop" /></label><label>Delivery Profile<input name="deliveryProfile" defaultValue="default" /></label><label>zhanlu-core ref<input name="zhanluCoreRef" list="refs" defaultValue="develop" /></label><label>zhanlu-vs ref<input name="zhanluVsRef" list="refs" defaultValue="develop" /></label></div><label><span><input type="checkbox" name="bundleCodexRuntime" /> 打包 Codex runtime</span></label><label><span><input type="checkbox" name="syncGitLab" defaultChecked /> 同步 GitLab 组件 Release（formal）</span></label><label><span><input type="checkbox" name="publish" /> 正式发布（仅 formal，确认时需输入短语）</span></label><button type="submit">生成预览</button></form><p>{message}</p></section><aside className="panel"><h2>管理员登录</h2><form action={login}><input name="username" autoComplete="username" placeholder="用户名" /><input name="password" type="password" autoComplete="current-password" placeholder="密码" /><button>登录</button></form><h2 style={{marginTop:32}}>最近构建</h2>{builds.map((build) => <div key={build.id} style={{marginBottom:18}}><span className="status">{build.phase}</span><br/><code>{build.spec.kind} {build.resolved?.releaseVersion??build.spec.version} · {build.spec.platform}</code><div style={{display:"flex",gap:8,marginTop:8}}>{build.phase==="awaiting_confirmation"&&<button onClick={()=>action(build,"confirm")}>确认</button>}{!["succeeded","failed","cancelled","needs_attention"].includes(build.phase)&&<button className="secondary" onClick={()=>action(build,"cancel")}>取消</button>}{build.phase==="failed"&&<button className="secondary" onClick={()=>action(build,"retry")}>重试失败平台</button>}</div></div>)}</aside></div>;
}
